[master]
BinaryName = 'testplan_0500'

[custom]
BinaryName = 'testplan_0500'

[[groups]]
Id = '0.49.0'
BinaryName = 'testplan_0490'

[[groups]]
Id = '0.48.0'
BinaryName = 'testplan_0480'

[[groups]]
Id = "v0.47.0"
BinaryName = 'testplan_0470'

[[groups]]
Id = "v0.46.0"
BinaryName = 'testplan_0460'

[[groups]]
Id = "v0.45.1"
BinaryName = 'testplan_0450'

[[groups]]
Id = "v0.44.0"
BinaryName = 'testplan_0440'
