[master]
CargoFeatures = 'libp2pmaster'

[custom]
CargoFeatures = 'libp2pmaster'

[[groups]]
Id = '0.49.0'
CargoFeatures = 'libp2pv0490'

[[groups]]
Id = '0.48.0'
CargoFeatures = 'libp2pv0480'

[[groups]]
Id = "v0.47.0"
CargoFeatures = 'libp2pv0470'

[[groups]]
Id = "v0.46.0"
CargoFeatures = 'libp2pv0460'

[[groups]]
Id = "v0.45.1"
CargoFeatures = 'libp2pv0450'

[[groups]]
Id = "v0.44.0"
CargoFeatures = 'libp2pv0440'
