#!/bin/bash

# Find the path to the Node.js executable
node_path=$(which node)

# Check if Node.js is installed
if [ -z "$node_path" ]; then
  echo "Node.js is not installed or not in the PATH."
  exit 1
fi

run_server=false
server_address=""
upload_bytes=0
download_bytes=0
transport=""

# Parse named parameters manually
for arg in "$@"; do
    case "$arg" in
        -r=*| --run_server=*) run_server="${arg#*=}";;
        -s=*| --server_address=*) server_address="${arg#*=}";;
        -u=*| --upload_bytes=*) upload_bytes="${arg#*=}";;
        -d=*| --download_bytes=*) download_bytes="${arg#*=}";;
        -t=*| --transport=*) transport="${arg#*=}";;
    esac
done

# cd into perf
cd perf-tests

# Run perf
node dist/src/main.js --run_server=$run_server --server_address=$server_address --upload_bytes=$upload_bytes --download_bytes=$download_bytes --transport=$transport
