#!/bin/bash

# Find the path to the Node.js executable
node_path=$(which node)

# Check if Node.js is installed
if [ -z "$node_path" ]; then
  echo "Node.js is not installed or not in the PATH."
  exit 1
fi

# Check if the Node.js script exists
if [ ! -f "$node_script" ]; then
  echo "Node.js script not found: $node_script"
  exit 1
fi

# cd into perf
cd perf-tests

# Run perf
node dist/src/main.js
