name: "Detect Changed Implementations"
description: "Detect which implementations/relays/routers have changed in impls.yaml or impls/ folder during a PR"

inputs:
  test-type:
    description: "Type of test (transport or hole-punch)"
    required: true
  base-ref:
    description: "Base branch to compare against"
    required: false
    default: "master"

outputs:
  changed-impls:
    description: "Pipe-separated list of changed implementation IDs"
    value: ${{ steps.detect.outputs.changed-impls }}
  changed-relays:
    description: "Pipe-separated list of changed relay IDs (hole-punch only)"
    value: ${{ steps.detect.outputs.changed-relays }}
  changed-routers:
    description: "Pipe-separated list of changed router IDs (hole-punch only)"
    value: ${{ steps.detect.outputs.changed-routers }}
  has-changes:
    description: "Boolean indicating if any changes were detected"
    value: ${{ steps.detect.outputs.has-changes }}
  impls-yaml-changed:
    description: "Boolean indicating if impls.yaml file changed"
    value: ${{ steps.detect.outputs.impls-yaml-changed }}
  impls-folder-changed:
    description: "Boolean indicating if impls/ folder changed"
    value: ${{ steps.detect.outputs.impls-folder-changed }}
  build-scripts-changed:
    description: "Boolean indicating if build/test scripts changed"
    value: ${{ steps.detect.outputs.build-scripts-changed }}

runs:
  using: "composite"
  steps:
    - name: Detect changes with path-based matching
      id: detect
      shell: bash
      run: |
        set -euo pipefail

        TEST_TYPE="${{ inputs.test-type }}"
        BASE_REF="${{ inputs.base-ref }}"

        # Set paths based on test type
        if [ "$TEST_TYPE" = "transport" ]; then
          IMPLS_FILE="transport/impls.yaml"
          IMPLS_DIR="transport/impls"
        elif [ "$TEST_TYPE" = "hole-punch" ]; then
          IMPLS_FILE="hole-punch/impls.yaml"
          IMPLS_DIR="hole-punch/impls"
        else
          echo "Error: Invalid test-type. Must be 'transport' or 'hole-punch'"
          exit 1
        fi

        echo "→ Analyzing changes for $TEST_TYPE tests"

        # Get list of all changed files
        CHANGED_FILES=$(git diff --name-only "origin/$BASE_REF"...HEAD)

        # Initialize outputs
        CHANGED_IMPLS=""
        CHANGED_RELAYS=""
        CHANGED_ROUTERS=""
        IMPLS_YAML_CHANGED="false"
        IMPLS_FOLDER_CHANGED="false"
        BUILD_SCRIPTS_CHANGED="false"

        # =================================================================
        # PART 1: Check if impls.yaml itself changed
        # =================================================================
        if echo "$CHANGED_FILES" | grep -q "^$IMPLS_FILE$"; then
          echo "→ $IMPLS_FILE changed - analyzing YAML diff"
          IMPLS_YAML_CHANGED="true"

          # Extract changed implementation IDs from YAML diff
          git show "origin/$BASE_REF:$IMPLS_FILE" > /tmp/impls-old.yaml 2>/dev/null || echo "" > /tmp/impls-old.yaml
          cp "$IMPLS_FILE" /tmp/impls-new.yaml

          # Find changed/new implementations
          OLD_IMPLS=$(yq eval '.implementations[].id' /tmp/impls-old.yaml 2>/dev/null | sort || echo "")
          NEW_IMPLS=$(yq eval '.implementations[].id' /tmp/impls-new.yaml 2>/dev/null | sort || echo "")

          for impl_id in $NEW_IMPLS; do
            if echo "$OLD_IMPLS" | grep -q "^${impl_id}$"; then
              # Exists in old, check if content changed
              OLD_IMPL=$(yq eval ".implementations[] | select(.id == \"$impl_id\")" /tmp/impls-old.yaml 2>/dev/null || echo "")
              NEW_IMPL=$(yq eval ".implementations[] | select(.id == \"$impl_id\")" /tmp/impls-new.yaml 2>/dev/null || echo "")

              if [ "$OLD_IMPL" != "$NEW_IMPL" ]; then
                CHANGED_IMPLS="${CHANGED_IMPLS:+$CHANGED_IMPLS|}$impl_id"
                echo "  → Changed implementation: $impl_id"
              fi
            else
              # New implementation
              CHANGED_IMPLS="${CHANGED_IMPLS:+$CHANGED_IMPLS|}$impl_id"
              echo "  → New implementation: $impl_id"
            fi
          done

          # For hole-punch: also check relays and routers
          if [ "$TEST_TYPE" = "hole-punch" ]; then
            # Check relays
            OLD_RELAYS=$(yq eval '.relays[].id' /tmp/impls-old.yaml 2>/dev/null | sort || echo "")
            NEW_RELAYS=$(yq eval '.relays[].id' /tmp/impls-new.yaml 2>/dev/null | sort || echo "")

            for relay_id in $NEW_RELAYS; do
              if echo "$OLD_RELAYS" | grep -q "^${relay_id}$"; then
                OLD_RELAY=$(yq eval ".relays[] | select(.id == \"$relay_id\")" /tmp/impls-old.yaml 2>/dev/null || echo "")
                NEW_RELAY=$(yq eval ".relays[] | select(.id == \"$relay_id\")" /tmp/impls-new.yaml 2>/dev/null || echo "")
                if [ "$OLD_RELAY" != "$NEW_RELAY" ]; then
                  CHANGED_RELAYS="${CHANGED_RELAYS:+$CHANGED_RELAYS|}$relay_id"
                  echo "  → Changed relay: $relay_id"
                fi
              else
                CHANGED_RELAYS="${CHANGED_RELAYS:+$CHANGED_RELAYS|}$relay_id"
                echo "  → New relay: $relay_id"
              fi
            done

            # Check routers
            OLD_ROUTERS=$(yq eval '.routers[].id' /tmp/impls-old.yaml 2>/dev/null | sort || echo "")
            NEW_ROUTERS=$(yq eval '.routers[].id' /tmp/impls-new.yaml 2>/dev/null | sort || echo "")

            for router_id in $NEW_ROUTERS; do
              if echo "$OLD_ROUTERS" | grep -q "^${router_id}$"; then
                OLD_ROUTER=$(yq eval ".routers[] | select(.id == \"$router_id\")" /tmp/impls-old.yaml 2>/dev/null || echo "")
                NEW_ROUTER=$(yq eval ".routers[] | select(.id == \"$router_id\")" /tmp/impls-new.yaml 2>/dev/null || echo "")
                if [ "$OLD_ROUTER" != "$NEW_ROUTER" ]; then
                  CHANGED_ROUTERS="${CHANGED_ROUTERS:+$CHANGED_ROUTERS|}$router_id"
                  echo "  → Changed router: $router_id"
                fi
              else
                CHANGED_ROUTERS="${CHANGED_ROUTERS:+$CHANGED_ROUTERS|}$router_id"
                echo "  → New router: $router_id"
              fi
            done
          fi

          rm -f /tmp/impls-old.yaml /tmp/impls-new.yaml
        fi

        # =================================================================
        # PART 2: Check if files in impls/ subfolder changed
        # =================================================================
        IMPLS_FOLDER_FILES=$(echo "$CHANGED_FILES" | grep "^$IMPLS_DIR/" || echo "")

        if [ -n "$IMPLS_FOLDER_FILES" ]; then
          echo "→ Files in $IMPLS_DIR/ changed - matching to local components"
          IMPLS_FOLDER_CHANGED="true"

          # Process each changed file
          while IFS= read -r changed_file; do
            [ -z "$changed_file" ] && continue

            # Get the directory path of the changed file
            FILE_DIR=$(dirname "$changed_file")

            echo "  → Analyzing: $changed_file"

            # Check implementations with source.type = local
            IMPL_COUNT=$(yq eval '.implementations | length' "$IMPLS_FILE" 2>/dev/null || echo "0")
            for ((i=0; i<IMPL_COUNT; i++)); do
              SOURCE_TYPE=$(yq eval ".implementations[$i].source.type" "$IMPLS_FILE" 2>/dev/null)
              if [ "$SOURCE_TYPE" = "local" ]; then
                SOURCE_PATH=$(yq eval ".implementations[$i].source.path" "$IMPLS_FILE")
                # Construct full path for comparison
                if [ "$TEST_TYPE" = "transport" ]; then
                  FULL_SOURCE_PATH="transport/$SOURCE_PATH"
                else
                  FULL_SOURCE_PATH="hole-punch/$SOURCE_PATH"
                fi

                # Check if changed file is within this source path
                if [[ "$changed_file" == "$FULL_SOURCE_PATH"* ]]; then
                  IMPL_ID=$(yq eval ".implementations[$i].id" "$IMPLS_FILE")
                  # Add to list if not already present
                  if [[ "|$CHANGED_IMPLS|" != *"|$IMPL_ID|"* ]]; then
                    CHANGED_IMPLS="${CHANGED_IMPLS:+$CHANGED_IMPLS|}$IMPL_ID"
                    echo "    ✓ Matched to implementation: $IMPL_ID"
                  fi
                fi
              fi
            done

            # For hole-punch: also check relays and routers
            if [ "$TEST_TYPE" = "hole-punch" ]; then
              # Check relays
              RELAY_COUNT=$(yq eval '.relays | length' "$IMPLS_FILE" 2>/dev/null || echo "0")
              for ((i=0; i<RELAY_COUNT; i++)); do
                SOURCE_TYPE=$(yq eval ".relays[$i].source.type" "$IMPLS_FILE" 2>/dev/null)
                if [ "$SOURCE_TYPE" = "local" ]; then
                  SOURCE_PATH=$(yq eval ".relays[$i].source.path" "$IMPLS_FILE")
                  FULL_SOURCE_PATH="hole-punch/$SOURCE_PATH"

                  if [[ "$changed_file" == "$FULL_SOURCE_PATH"* ]]; then
                    RELAY_ID=$(yq eval ".relays[$i].id" "$IMPLS_FILE")
                    if [[ "|$CHANGED_RELAYS|" != *"|$RELAY_ID|"* ]]; then
                      CHANGED_RELAYS="${CHANGED_RELAYS:+$CHANGED_RELAYS|}$RELAY_ID"
                      echo "    ✓ Matched to relay: $RELAY_ID"
                    fi
                  fi
                fi
              done

              # Check routers
              ROUTER_COUNT=$(yq eval '.routers | length' "$IMPLS_FILE" 2>/dev/null || echo "0")
              for ((i=0; i<ROUTER_COUNT; i++)); do
                SOURCE_TYPE=$(yq eval ".routers[$i].source.type" "$IMPLS_FILE" 2>/dev/null)
                if [ "$SOURCE_TYPE" = "local" ]; then
                  SOURCE_PATH=$(yq eval ".routers[$i].source.path" "$IMPLS_FILE")
                  FULL_SOURCE_PATH="hole-punch/$SOURCE_PATH"

                  if [[ "$changed_file" == "$FULL_SOURCE_PATH"* ]]; then
                    ROUTER_ID=$(yq eval ".routers[$i].id" "$IMPLS_FILE")
                    if [[ "|$CHANGED_ROUTERS|" != *"|$ROUTER_ID|"* ]]; then
                      CHANGED_ROUTERS="${CHANGED_ROUTERS:+$CHANGED_ROUTERS|}$ROUTER_ID"
                      echo "    ✓ Matched to router: $ROUTER_ID"
                    fi
                  fi
                fi
              done
            fi
          done <<< "$IMPLS_FOLDER_FILES"
        fi

        # =================================================================
        # PART 3: Check if build/test scripts changed
        # =================================================================
        if [ "$TEST_TYPE" = "transport" ]; then
          BUILD_SCRIPT_PATTERNS="transport/scripts/|transport/run_tests.sh"
        elif [ "$TEST_TYPE" = "hole-punch" ]; then
          BUILD_SCRIPT_PATTERNS="hole-punch/scripts/|hole-punch/run_tests.sh"
        fi

        BUILD_SCRIPT_FILES=$(echo "$CHANGED_FILES" | grep -E "^($BUILD_SCRIPT_PATTERNS)" || echo "")

        if [ -n "$BUILD_SCRIPT_FILES" ]; then
          echo "→ Build/test scripts changed - will trigger tests for all implementations"
          BUILD_SCRIPTS_CHANGED="true"
          echo "$BUILD_SCRIPT_FILES" | while IFS= read -r changed_file; do
            [ -z "$changed_file" ] && continue
            echo "  → Changed script: $changed_file"
          done
        fi

        # Output all results
        echo "changed-impls=$CHANGED_IMPLS" >> $GITHUB_OUTPUT
        echo "changed-relays=$CHANGED_RELAYS" >> $GITHUB_OUTPUT
        echo "changed-routers=$CHANGED_ROUTERS" >> $GITHUB_OUTPUT
        echo "impls-yaml-changed=$IMPLS_YAML_CHANGED" >> $GITHUB_OUTPUT
        echo "impls-folder-changed=$IMPLS_FOLDER_CHANGED" >> $GITHUB_OUTPUT
        echo "build-scripts-changed=$BUILD_SCRIPTS_CHANGED" >> $GITHUB_OUTPUT

        # Set has-changes
        # Trigger tests if implementations changed OR if build scripts changed
        if [ -n "$CHANGED_IMPLS" ] || [ -n "$CHANGED_RELAYS" ] || [ -n "$CHANGED_ROUTERS" ] || [ "$BUILD_SCRIPTS_CHANGED" = "true" ]; then
          echo "has-changes=true" >> $GITHUB_OUTPUT
          if [ "$BUILD_SCRIPTS_CHANGED" = "true" ]; then
            echo "→ Summary: Build scripts changed - will test all implementations"
          else
            echo "→ Summary: impls=$CHANGED_IMPLS, relays=$CHANGED_RELAYS, routers=$CHANGED_ROUTERS"
          fi
        else
          echo "has-changes=false" >> $GITHUB_OUTPUT
          echo "→ No relevant changes detected"
        fi
