[metadata]
  name = "all-cypress"
  author = "adin"

[global]
  plan = "dht"
  case = "all"
  total_instances = 1170
  builder = "docker:go"
  runner = "cluster:k8s"
  [global.build_config]
    push_registry = true
    registry_type = "aws"

[[groups]]
  id = "cypress-passive"
  [groups.instances]
    count = 1020
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "180be07b8303d536e39809bc39c58be5407fedd9"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-xor"
      version = "df24f5b04bcbdc0059b27989163a6090f4f6dc7a"
  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "1"
      latency = "100"
      timeout_secs = "600"

[[groups]]
  id = "cypress-provider-small"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "180be07b8303d536e39809bc39c58be5407fedd9"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-xor"
      version = "df24f5b04bcbdc0059b27989163a6090f4f6dc7a"
  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "4"
      latency = "100"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "cypress-provider-medium"
  [groups.instances]
    count = 15
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "180be07b8303d536e39809bc39c58be5407fedd9"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-xor"
      version = "df24f5b04bcbdc0059b27989163a6090f4f6dc7a"
  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "3"
      latency = "100"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "cypress-provider-large"
  [groups.instances]
    count = 100
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "180be07b8303d536e39809bc39c58be5407fedd9"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-xor"
      version = "df24f5b04bcbdc0059b27989163a6090f4f6dc7a"
  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "2"
      latency = "100"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "cypress-searcher"
  [groups.instances]
    count = 25
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "180be07b8303d536e39809bc39c58be5407fedd9"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-xor"
      version = "df24f5b04bcbdc0059b27989163a6090f4f6dc7a"
  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "5"
      latency = "100"
      n_find_peers = "5"
      search_records = "true"
      timeout_secs = "600"

[[groups]]
  id = "cypress-bs"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "180be07b8303d536e39809bc39c58be5407fedd9"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-xor"
      version = "df24f5b04bcbdc0059b27989163a6090f4f6dc7a"
  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "0"
      latency = "100"
      timeout_secs = "600"
