[metadata]
  name = "find-provs"
  author = "adin"

[global]
  plan = "dht"
  case = "find-providers"
  total_instances = 1000
  builder = "docker:go"
  runner = "cluster:k8s"
  [global.build_config]
    push_registry = true
    registry_type = "aws"

[[groups]]
  id = "balsam-undialable-provider-small"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    selectors = ["balsam"]
  [groups.run]
    [groups.run.test_params]
      bs_strategy = "6"
      bucket_size = "10"
      record_count = "1"
      timeout_secs = "600"
      undialable = "true"

[[groups]]
  id = "balsam-undialable-provider-medium"
  [groups.instances]
    count = 15
    percentage = 0.0
  [groups.build]
    selectors = ["balsam"]
  [groups.run]
    [groups.run.test_params]
      bs_strategy = "6"
      bucket_size = "10"
      record_count = "1"
      timeout_secs = "600"
      undialable = "true"

[[groups]]
  id = "balsam-undialable-provider-large"
  [groups.instances]
    count = 100
    percentage = 0.0
  [groups.build]
    selectors = ["balsam"]
  [groups.run]
    [groups.run.test_params]
      bs_strategy = "6"
      bucket_size = "10"
      record_count = "1"
      timeout_secs = "600"
      undialable = "true"

[[groups]]
  id = "balsam-dialable-provider-small"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    selectors = ["balsam"]
  [groups.run]
    [groups.run.test_params]
      bs_strategy = "6"
      bucket_size = "10"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "balsam-dialable-provider-medium"
  [groups.instances]
    count = 15
    percentage = 0.0
  [groups.build]
    selectors = ["balsam"]
  [groups.run]
    [groups.run.test_params]
      bs_strategy = "6"
      bucket_size = "10"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "balsam-dialable-provider-large"
  [groups.instances]
    count = 100
    percentage = 0.0
  [groups.build]
    selectors = ["balsam"]
  [groups.run]
    [groups.run.test_params]
      bs_strategy = "6"
      bucket_size = "10"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "balsam-undialable-searcher"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    selectors = ["balsam"]
  [groups.run]
    [groups.run.test_params]
      bs_strategy = "6"
      bucket_size = "10"
      search_records = "true"
      timeout_secs = "600"
      undialable = "true"

[[groups]]
  id = "balsam-dialable-searcher"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    selectors = ["balsam"]
  [groups.run]
    [groups.run.test_params]
      bs_strategy = "6"
      bucket_size = "10"
      search_records = "true"
      timeout_secs = "600"

[[groups]]
  id = "balsam-undialable-passive"
  [groups.instances]
    count = 495
    percentage = 0.0
  [groups.build]
    selectors = ["balsam"]
  [groups.run]
    [groups.run.test_params]
      bs_strategy = "6"
      bucket_size = "10"
      timeout_secs = "600"
      undialable = "true"

[[groups]]
  id = "balsam-dialable-passive"
  [groups.instances]
    count = 250
    percentage = 0.0
  [groups.build]
    selectors = ["balsam"]
  [groups.run]
    [groups.run.test_params]
      bs_strategy = "6"
      bucket_size = "10"
      timeout_secs = "600"

[[groups]]
  id = "balsam-bs"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    selectors = ["balsam"]
  [groups.run]
    [groups.run.test_params]
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      timeout_secs = "600"


