name: "libp2p hole-punch interop test (self hosted)"
description: "Run the libp2p hole-punch interoperability test suite"
inputs:
  test-filter:
    description: "Filter which tests to run out of the created matrix"
    required: false
    default: ""
  test-ignore:
    description: "Exclude tests from the created matrix that include this string in their name"
    required: false
    default: ""
  upload-results:
    description: "Upload the test results as an artifact"
    required: false
    default: "true"
  extra-versions:
    description: "Space-separated paths to JSON files describing additional images"
    required: false
    default: ""
  s3-cache-bucket:
    description: "Which S3 bucket to use for container layer caching"
    required: false
    default: ""
  s3-access-key-id:
    description: "S3 Access key id for the cache"
    required: false
    default: ""
  s3-secret-access-key:
    description: "S3 secret key id for the cache"
    required: false
    default: ""
  aws-region:
    description: "Which AWS region to use"
    required: false
    default: "us-east-1"
  worker-count:
    description: "How many workers to use for the test"
    required: false
    default: "2"
  cache-dir:
    description: "Local directory to use for build cache"
    required: false
    default: "/srv/cache"
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials for S3 build cache
      if: inputs.s3-access-key-id != '' && inputs.s3-secret-access-key != ''
      run: |
        echo "PUSH_CACHE=true" >> $GITHUB_ENV
      shell: bash

    # This depends on where this file is within this repository. This walks up
    # from here to the hole-punch-interop folder
    - run: |
        WORK_DIR=$(realpath "$GITHUB_ACTION_PATH/../../../hole-punch-interop")
        echo "WORK_DIR=$WORK_DIR" >> $GITHUB_OUTPUT
      shell: bash
      id: find-workdir

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    # Existence of /etc/buildkit/buildkitd.toml indicates that this is a
    # self-hosted runner. If so, we need to pass the config to the buildx
    # action. The config enables docker.io proxy which is required to
    # work around docker hub rate limiting.
    - run: |
        if test -f /etc/buildkit/buildkitd.toml; then
          echo "config=/etc/buildkit/buildkitd.toml" >> $GITHUB_OUTPUT
        fi
      shell: bash
      id: buildkit

    - name: Install more recent docker-compose version # https://stackoverflow.com/questions/54331949/having-networking-issues-with-docker-compose
      shell: bash
      run: |
        mkdir -p $HOME/.docker/cli-plugins
        wget -q -O- https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-linux-x86_64 > $HOME/.docker/cli-plugins/docker-compose
        chmod +x $HOME/.docker/cli-plugins/docker-compose
        docker compose version

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        config: ${{ steps.buildkit.outputs.config }}

    - name: Create cache directories
      run: |
        mkdir -p ${{ inputs.cache-dir }}/buildCache
        mkdir -p ${{ inputs.cache-dir }}/imageCache
      shell: bash

    - name: Install deps
      working-directory: ${{ steps.find-workdir.outputs.WORK_DIR }}
      run: npm ci
      shell: bash

    - name: Load cache and build
      working-directory: ${{ steps.find-workdir.outputs.WORK_DIR }}
      env:
        CACHE_DIR: ${{ inputs.cache-dir }}
        NAME_FILER: ${{ inputs.test-filter }}
        NAME_IGNORE: ${{ inputs.test-ignore }}
        VERBOSE: ${{ inputs.verbose }}
      run: npm run cache -- load --name-filter="$NAME_FILTER" --name-ignore="$NAME_IGNORE" --verbose="$VERBOSE"
      shell: bash

    - name: Assert Git tree is clean.
      working-directory: ${{ steps.find-workdir.outputs.WORK_DIR }}
      shell: bash
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "Git tree is dirty. This means that building an impl generated something that should probably be .gitignore'd"
          git status
          exit 1
        fi

    - name: Push the image cache
      if: env.PUSH_CACHE == 'true'
      working-directory: ${{ steps.find-workdir.outputs.WORK_DIR }}
      env:
        CACHE_DIR: ${{ inputs.cache-dir }}
        NAME_FILTER: ${{ inputs.test-filter }}
        NAME_IGNORE: ${{ inputs.test-ignore }}
        VERBOSE: ${{ inputs.verbose }}
      run: npm run cache -- push --name-filter="$NAME_FILTER" --name-ignore="$NAME_IGNORE" --verbose="$VERBOSE"
      shell: bash

    - name: Run the test
      working-directory: ${{ steps.find-workdir.outputs.WORK_DIR }}
      env:
        WORKER_COUNT: ${{ inputs.worker-count }}
        EXTRA_VERSION: ${{ inputs.extra-versions }}
        NAME_FILTER: ${{ inputs.test-filter }}
        NAME_IGNORE: ${{ inputs.test-ignore }}
        TIMEOUT: ${{ inputs.timeout }}
        VERBOSE: ${{ inputs.verbose }}
      run: npm run test -- --extra-version=$EXTRA_VERSION --name-filter=$NAME_FILTER --name-ignore=$NAME_IGNORE --verbose=$VERBOSE
      shell: bash

    - name: Print the results
      working-directory: ${{ steps.find-workdir.outputs.WORK_DIR }}
      run: cat results.csv
      shell: bash

    - name: Render results
      working-directory: ${{ steps.find-workdir.outputs.WORK_DIR }}
      run: npm run renderResults > ./dashboard.md
      shell: bash

    - name: Show Dashboard Output
      working-directory: ${{ steps.find-workdir.outputs.WORK_DIR }}
      run: cat ./dashboard.md >> $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Upload test results
      if: ${{ always() && inputs.upload-results == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: test-plans-output
        path: |
          ${{ steps.find-workdir.outputs.WORK_DIR }}/results.csv
          ${{ steps.find-workdir.outputs.WORK_DIR }}/dashboard.md
          ${{ steps.find-workdir.outputs.WORK_DIR }}/runs
