name: Build Go

on:
  push:
    branches: [master, publish-images]
    paths:
      - "transport-interop/impl/go/**"
      - ".github/workflows/go.yml"
      - ".github/workflows/build-and-publish.yml"
      - ".github/scripts/compute-cache-key.mjs"
  pull_request:
    branches: [master]
    paths:
      - "transport-interop/impl/go/**"
      - ".github/workflows/go.yml"
      - ".github/workflows/build-and-publish.yml"
      - ".github/scripts/compute-cache-key.mjs"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-and-publish.yml
    with:
      implementation: go
