name: Build Go

on:
  push:
    branches: [master]
    paths:
      - "transport-interop/impl/go/**"
  pull_request:
    branches: [master]
    paths:
      - "transport-interop/impl/go/**"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-and-publish.yml
    with:
      implementation: go
